Parameters:
  Environment:
    Type: 'String'
    Default: 'test'
Resources:
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lambda-code-virtual-number-${Environment}"
Outputs:
  LambdaS3Bucket:
    Description: Lambda S3 bucket for storing the code which is executed on the Lambda platform.
    Value: !Ref LambdaBucket
    Export:
      Name: !Sub "lambda-s3-bucket-${Environment}"