spring:
  cloud:
    function:
      web:
        export:
          enabled: false
default:
  voice:
    answer:
      text: "<speak>Hello, Thank you for calling. I'm currently not available to take this call.</speak>"